create table ai_chat_messages (created_at datetime(6) not null, id bigint not null auto_increment, thread_id bigint not null, role varchar(20) not null, model varchar(120), actions_json LONGTEXT not null, content LONGTEXT not null, references_json LONGTEXT not null, primary key (id)) engine=InnoDB;
create table ai_chat_threads (message_count integer not null, created_at datetime(6) not null, id bigint not null auto_increment, last_message_at datetime(6), updated_at datetime(6) not null, user_id bigint not null, last_message_role varchar(20), title varchar(180) not null, last_message_preview varchar(500), primary key (id)) engine=InnoDB;
create table cart_items (quantity integer not null, unit_price decimal(12,2) not null, cart_id bigint not null, created_at datetime(6) not null, dish_id bigint not null, id bigint not null auto_increment, store_id bigint not null, updated_at datetime(6) not null, primary key (id)) engine=InnoDB;
create table carts (created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6) not null, user_id bigint not null, status enum ('OPEN') not null, primary key (id)) engine=InnoDB;
create table categories (active bit not null, sort_order integer, created_at datetime(6) not null, id bigint not null auto_increment, store_id bigint, updated_at datetime(6) not null, name varchar(120) not null, description varchar(1000), primary key (id)) engine=InnoDB;
create table category_image_paths (sort_order integer not null, category_id bigint not null, image_path varchar(500), primary key (sort_order, category_id)) engine=InnoDB;
create table content_section_image_paths (sort_order integer not null, content_section_id bigint not null, image_path varchar(500), primary key (sort_order, content_section_id)) engine=InnoDB;
create table content_sections (sort_order integer not null, dish_id bigint, event_id bigint, id bigint not null auto_increment, news_article_id bigint, store_id bigint, title varchar(200) not null, image_path varchar(500), content TEXT not null, owner_type enum ('DISH','EVENT','NEWS_ARTICLE','STORE') not null, primary key (id)) engine=InnoDB;
create table customer_feedbacks (created_at datetime(6) not null, id bigint not null auto_increment, related_order_id bigint, related_store_id bigint, replied_at datetime(6), replied_by_user_id bigint, updated_at datetime(6) not null, user_id bigint not null, replied_by_user_name varchar(180), subject varchar(180) not null, message varchar(3000) not null, reply_message varchar(3000), category enum ('APP_EXPERIENCE','DELIVERY','GENERAL','ORDER_EXPERIENCE','OTHER','PRODUCT_QUALITY','STORE_SERVICE') not null, replied_by_user_role enum ('ADMIN','MANAGER','SHIPPER','USER'), primary key (id)) engine=InnoDB;
create table dish_highlight_tags (sort_order integer not null, dish_id bigint not null, highlight_tag varchar(160), primary key (sort_order, dish_id)) engine=InnoDB;
create table dish_image_paths (sort_order integer not null, dish_id bigint not null, image_path varchar(500), primary key (sort_order, dish_id)) engine=InnoDB;
create table dishes (active bit not null, available bit not null, franchise_required bit not null, price decimal(12,2) not null, category_id bigint not null, created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6) not null, status varchar(50), name varchar(150) not null, franchise_note varchar(1000), highlight_summary varchar(1000), note varchar(1000), description varchar(2000), primary key (id)) engine=InnoDB;
create table email_otps (used bit not null, created_at datetime(6) not null, expires_at datetime(6) not null, id bigint not null auto_increment, otp_code varchar(8) not null, used_at datetime(6), user_id bigint not null, purpose enum ('PASSWORD_RESET','REGISTER_VERIFY'), primary key (id)) engine=InnoDB;
create table employee_attendances (work_date date not null, check_in_at datetime(6) not null, check_out_at datetime(6), created_at datetime(6) not null, id bigint not null auto_increment, store_id bigint not null, updated_at datetime(6) not null, user_id bigint not null, work_schedule_id bigint, employee_role enum ('ADMIN','MANAGER','SHIPPER','USER') not null, primary key (id)) engine=InnoDB;
create table employee_work_schedules (scheduled_end_time time(6) not null, scheduled_start_time time(6) not null, work_date date not null, created_at datetime(6) not null, id bigint not null auto_increment, store_id bigint not null, updated_at datetime(6) not null, user_id bigint not null, note varchar(1000), employee_role enum ('ADMIN','MANAGER','SHIPPER','USER') not null, primary key (id)) engine=InnoDB;
create table event_featured_dish_ids (sort_order integer not null, dish_id bigint not null, event_id bigint not null, primary key (sort_order, event_id)) engine=InnoDB;
create table event_highlight_tags (sort_order integer not null, event_id bigint not null, highlight_tag varchar(160), primary key (sort_order, event_id)) engine=InnoDB;
create table event_image_paths (sort_order integer not null, event_id bigint not null, image_path varchar(500), primary key (sort_order, event_id)) engine=InnoDB;
create table events (active bit not null, booked_count integer not null, capacity integer, created_at datetime(6) not null, ends_at datetime(6) not null, id bigint not null auto_increment, starts_at datetime(6) not null, store_id bigint not null, updated_at datetime(6) not null, name varchar(150) not null, slug varchar(200), highlight_summary varchar(1000), description varchar(2000), location varchar(255), schedule_text varchar(255), primary key (id)) engine=InnoDB;
create table favorites (created_at datetime(6) not null, id bigint not null auto_increment, target_id bigint not null, user_id bigint not null, target_type enum ('DISH','EVENT','STORE') not null, primary key (id)) engine=InnoDB;
create table news_article_image_paths (sort_order integer not null, news_article_id bigint not null, image_path varchar(500), primary key (sort_order, news_article_id)) engine=InnoDB;
create table news_article_tags (sort_order integer not null, news_article_id bigint not null, tag varchar(120), primary key (sort_order, news_article_id)) engine=InnoDB;
create table news_articles (featured bit not null, published bit not null, created_at datetime(6) not null, id bigint not null auto_increment, published_at datetime(6), related_store_id bigint, updated_at datetime(6) not null, title varchar(180) not null, slug varchar(200) not null, summary varchar(500) not null, content TEXT not null, primary key (id)) engine=InnoDB;
create table order_items (quantity integer not null, unit_price decimal(12,2) not null, created_at datetime(6) not null, dish_id bigint not null, id bigint not null auto_increment, order_id bigint not null, store_id bigint not null, updated_at datetime(6) not null, primary key (id)) engine=InnoDB;
create table order_promotion_dish_ids (sort_order integer not null, dish_id bigint not null, order_id bigint not null, primary key (sort_order, order_id)) engine=InnoDB;
create table order_scan_audits (success bit not null, id bigint not null auto_increment, order_id bigint not null, scanned_at datetime(6) not null, scanned_by_user_id bigint, scanned_by_user_name varchar(180), failure_reason varchar(500), action enum ('ACCEPT_DELIVERY','ACCEPT_PREPARING') not null, role enum ('ADMIN','MANAGER','SHIPPER','USER'), primary key (id)) engine=InnoDB;
create table orders (discount_amount decimal(12,2) not null, promotion_eligible_amount decimal(12,2), subtotal_amount decimal(12,2) not null, total_amount decimal(12,2) not null, confirmed_at datetime(6), confirmed_by_user_id bigint, created_at datetime(6) not null, delivering_shipper_id bigint, delivery_address_id bigint, delivery_proof_captured_at datetime(6), delivery_proof_uploaded_at datetime(6), id bigint not null auto_increment, invoice_issued_at datetime(6), paid_at datetime(6), payment_expires_at datetime(6), payos_order_code bigint, preparing_staff_id bigint, scheduled_delivery_at datetime(6), updated_at datetime(6) not null, user_id bigint not null, delivery_phone_number varchar(30), payment_provider varchar(30), promotion_code varchar(50), delivery_full_name varchar(100), payment_link_id varchar(100), payment_reference varchar(100), invoice_number varchar(120), delivery_proof_image_path varchar(500), delivery_proof_note varchar(500), payment_cancel_url varchar(500), payment_checkout_url varchar(500), payment_return_url varchar(500), payment_qr_code varchar(4000), delivery_address varchar(255), invoice_qr_token varchar(255), delivery_type enum ('IMMEDIATE','SCHEDULED') not null, payment_status enum ('CANCELLED','FAILED','PAID','PENDING') not null, promotion_scope enum ('DISH','ORDER'), status enum ('CANCELLED','COMPLETED','CONFIRMED','OUT_FOR_DELIVERY','PENDING','PREPARING','READY_FOR_SHIPPER') not null, primary key (id)) engine=InnoDB;
create table promotion_applicable_dishes (sort_order integer not null, dish_id bigint not null, promotion_id bigint not null, primary key (sort_order, promotion_id)) engine=InnoDB;
create table promotion_eligible_stores (sort_order integer not null, promotion_id bigint not null, store_id bigint not null, primary key (sort_order, promotion_id)) engine=InnoDB;
create table promotion_eligible_user_levels (sort_order integer not null, promotion_id bigint not null, user_level_id bigint not null, primary key (sort_order, promotion_id)) engine=InnoDB;
create table promotions (active bit not null, discount_value decimal(12,2) not null, max_discount_amount decimal(12,2), min_cross_store_bill_amount decimal(12,2), min_order_amount decimal(12,2), min_store_bill_amount decimal(12,2), usage_limit integer, used_count integer not null, created_at datetime(6) not null, ends_at datetime(6), id bigint not null auto_increment, starts_at datetime(6), updated_at datetime(6) not null, code varchar(50) not null, name varchar(150), description varchar(500), discount_type enum ('FIXED_AMOUNT','PERCENT') not null, scope enum ('DISH','ORDER') not null, primary key (id)) engine=InnoDB;
create table reviews (approved bit not null, rating integer not null, created_at datetime(6) not null, id bigint not null auto_increment, target_id bigint not null, updated_at datetime(6) not null, user_id bigint not null, title varchar(150), comment varchar(2000), target_type enum ('CATEGORY','DISH','EVENT','STORE') not null, primary key (id)) engine=InnoDB;
create table store_dishes (available bit not null, price_override decimal(12,2), quantity integer not null, created_at datetime(6) not null, dish_id bigint not null, id bigint not null auto_increment, store_id bigint not null, updated_at datetime(6) not null, primary key (id)) engine=InnoDB;
create table store_highlight_tags (sort_order integer not null, store_id bigint not null, highlight_tag varchar(160), primary key (sort_order, store_id)) engine=InnoDB;
create table store_image_paths (sort_order integer not null, store_id bigint not null, image_path varchar(500), primary key (sort_order, store_id)) engine=InnoDB;
create table store_service_tags (sort_order integer not null, store_id bigint not null, service_tag varchar(120), primary key (sort_order, store_id)) engine=InnoDB;
create table stores (active bit not null, close_time time(6), latitude float(53), longitude float(53), open_time time(6), created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6) not null, phone_number varchar(30), area varchar(120), contact_email varchar(150), name varchar(150) not null, position_label varchar(150), slug varchar(180), highlight_summary varchar(1000), description varchar(2000), address varchar(255), design_signature varchar(255), franchise_mood varchar(255), hours_text varchar(255), personality varchar(255), specialty varchar(255), primary key (id)) engine=InnoDB;
create table user_delivery_addresses (is_primary bit, created_at datetime(6) not null, id bigint not null auto_increment, last_used_at datetime(6), updated_at datetime(6) not null, user_id bigint not null, verified_at datetime(6), phone_number varchar(30) not null, full_name varchar(100) not null, delivery_address varchar(255) not null, primary key (id)) engine=InnoDB;
create table user_level_definitions (active bit not null, min_paid_amount decimal(12,2) not null, created_at datetime(6) not null, id bigint not null auto_increment, store_id bigint not null, updated_at datetime(6) not null, code varchar(50) not null, name varchar(120) not null, primary key (id)) engine=InnoDB;
create table user_notifications (created_at datetime(6) not null, id bigint not null auto_increment, read_at datetime(6), related_event_id bigint, related_news_id bigint, related_order_id bigint, related_store_id bigint, user_id bigint not null, related_store_name varchar(180), title varchar(180) not null, related_event_slug varchar(220), related_news_slug varchar(220), action_url varchar(500), message varchar(1000) not null, type enum ('BRAND_EVENT','NEWS_ARTICLE','ORDER_STATUS','ORDER_TASK') not null, primary key (id)) engine=InnoDB;
create table user_sessions (created_at datetime(6) not null, expires_at datetime(6) not null, id bigint not null auto_increment, user_id bigint not null, token varchar(255) not null, primary key (id)) engine=InnoDB;
create table users (enabled bit not null, profile_completed bit, created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6) not null, verified_at datetime(6), working_store_id bigint, full_name varchar(100) not null, password_hash varchar(100) not null, email varchar(150) not null, role enum ('ADMIN','MANAGER','SHIPPER','USER') not null, primary key (id)) engine=InnoDB;
create index idx_ai_chat_messages_thread_created on ai_chat_messages (thread_id, created_at);
create index idx_ai_chat_messages_thread_role on ai_chat_messages (thread_id, role);
create index idx_ai_chat_threads_user_updated on ai_chat_threads (user_id, updated_at);
create index idx_ai_chat_threads_user_created on ai_chat_threads (user_id, created_at);
create index idx_content_sections_owner_type on content_sections (owner_type);
create index idx_content_sections_store_sort on content_sections (store_id, sort_order);
create index idx_content_sections_dish_sort on content_sections (dish_id, sort_order);
create index idx_content_sections_event_sort on content_sections (event_id, sort_order);
create index idx_content_sections_news_sort on content_sections (news_article_id, sort_order);
create index idx_email_otps_user_id on email_otps (user_id);
create index idx_email_otps_expires_at on email_otps (expires_at);
alter table employee_attendances add constraint uk_employee_attendances_user_work_date unique (user_id, work_date);
alter table employee_work_schedules add constraint uk_employee_work_schedules_user_work_date unique (user_id, work_date);
alter table favorites add constraint uk_favorites_user_target unique (user_id, target_type, target_id);
alter table orders add constraint UK9euhgrj490gy02d8abquh7jvu unique (invoice_number);
alter table orders add constraint UKqi76d9mtc0wlg9e1idje9xhw7 unique (invoice_qr_token);
alter table promotions add constraint uk_promotions_code unique (code);
alter table reviews add constraint uk_reviews_user_target unique (user_id, target_type, target_id);
alter table store_dishes add constraint uk_store_dishes_store_dish unique (store_id, dish_id);
alter table user_level_definitions add constraint uk_user_level_store_code unique (store_id, code);
create index idx_user_sessions_user_id on user_sessions (user_id);
alter table user_sessions add constraint uk_user_sessions_token unique (token);
alter table users add constraint uk_users_email unique (email);
alter table ai_chat_messages add constraint FKouafb4eq0q2ep7ivou61i7e20 foreign key (thread_id) references ai_chat_threads (id);
alter table ai_chat_threads add constraint FKj5n8yrw10dqrrjv7wm11mujtr foreign key (user_id) references users (id);
alter table cart_items add constraint FKpcttvuq4mxppo8sxggjtn5i2c foreign key (cart_id) references carts (id);
alter table cart_items add constraint FKqf96jt4hthdxw36s3ebnq1yns foreign key (dish_id) references dishes (id);
alter table cart_items add constraint FK5hdx4t879kwd8w87xkhs9c6dq foreign key (store_id) references stores (id);
alter table carts add constraint FKb5o626f86h46m4s7ms6ginnop foreign key (user_id) references users (id);
alter table categories add constraint FKswh8ov7e46aj6bf053xla2c6b foreign key (store_id) references stores (id);
alter table category_image_paths add constraint FKb7y210s5ic11dttr4yr1llyn4 foreign key (category_id) references categories (id);
alter table content_section_image_paths add constraint FKorl3fvep2fv0okoeqsmb4jukw foreign key (content_section_id) references content_sections (id);
alter table content_sections add constraint FKm7gv696als9t9ck73nf2ukrl6 foreign key (dish_id) references dishes (id);
alter table content_sections add constraint FKbvufhtflhve84oghdadaao88r foreign key (event_id) references events (id);
alter table content_sections add constraint FK2kh8a6qv518gr1veqngle9gqk foreign key (news_article_id) references news_articles (id);
alter table content_sections add constraint FKcmt5nm5ikudadbe6npkkd447l foreign key (store_id) references stores (id);
alter table customer_feedbacks add constraint FKibq6vy2x1ahlhb6xj3c137x72 foreign key (related_order_id) references orders (id);
alter table customer_feedbacks add constraint FKrhc7t0imekdob5cw74bo80cju foreign key (related_store_id) references stores (id);
alter table customer_feedbacks add constraint FKou0o03ij4sesxchs0w9t7f7eq foreign key (user_id) references users (id);
alter table dish_highlight_tags add constraint FKakf5o111squqo1rp3348km9lr foreign key (dish_id) references dishes (id);
alter table dish_image_paths add constraint FKoaiumig5ojytqm745l7qpybos foreign key (dish_id) references dishes (id);
alter table dishes add constraint FKgbu6erefir17660qutbbjnma7 foreign key (category_id) references categories (id);
alter table email_otps add constraint FKi9ohg8k7e44e0tg90j9jtn3lw foreign key (user_id) references users (id);
alter table employee_attendances add constraint FKeg8icq9dx4k5wu41527tsjgcd foreign key (store_id) references stores (id);
alter table employee_attendances add constraint FKrvuddh4nc8k4cpy80j2tjeqbv foreign key (user_id) references users (id);
alter table employee_attendances add constraint FKd9ufks8a7mjknhm32m29lraxy foreign key (work_schedule_id) references employee_work_schedules (id);
alter table employee_work_schedules add constraint FKqc8bda3v77v5ww4to61go9wnn foreign key (store_id) references stores (id);
alter table employee_work_schedules add constraint FKoyi41tbb7uog4u666li3lh9fm foreign key (user_id) references users (id);
alter table event_featured_dish_ids add constraint FKk1n7ec7do2h847kb71scqasfo foreign key (event_id) references events (id);
alter table event_highlight_tags add constraint FK3ms16sdi8o6ksx5w2y6mna7la foreign key (event_id) references events (id);
alter table event_image_paths add constraint FKrftrd22bo6g7xlg2jrr4t0x70 foreign key (event_id) references events (id);
alter table events add constraint FKpl9v5uhqjwt011cx4r3bord5d foreign key (store_id) references stores (id);
alter table favorites add constraint FKk7du8b8ewipawnnpg76d55fus foreign key (user_id) references users (id);
alter table news_article_image_paths add constraint FK7q1my3u4g0asa8s7qbs1384pb foreign key (news_article_id) references news_articles (id);
alter table news_article_tags add constraint FKh3fwid8lf6p5uf49pbe49wmv3 foreign key (news_article_id) references news_articles (id);
alter table news_articles add constraint FK9g9684rmg6gucyv9jsg30xljs foreign key (related_store_id) references stores (id);
alter table order_items add constraint FKn06bdypik73hotpxvefsrtn77 foreign key (dish_id) references dishes (id);
alter table order_items add constraint FKbioxgbv59vetrxe0ejfubep1w foreign key (order_id) references orders (id);
alter table order_items add constraint FKokssvkh5oimo94ipqywams1hg foreign key (store_id) references stores (id);
alter table order_promotion_dish_ids add constraint FKpb68qq7dtmhb7uddhbbgml1qw foreign key (order_id) references orders (id);
alter table order_scan_audits add constraint FKg6i7lo2lxxe17ku0hdvi04n7x foreign key (order_id) references orders (id);
alter table orders add constraint FKfdm2g2oigekkih7c5yq3h5w8x foreign key (confirmed_by_user_id) references users (id);
alter table orders add constraint FKqt20of6jyjvt2vurdhh6t2q7v foreign key (delivering_shipper_id) references users (id);
alter table orders add constraint FKo2nbvrpk5u3t9kmo46pbam5wi foreign key (preparing_staff_id) references users (id);
alter table orders add constraint FK32ql8ubntj5uh44ph9659tiih foreign key (user_id) references users (id);
alter table promotion_applicable_dishes add constraint FKswbxvihwbt9jhpymnde2weh4f foreign key (promotion_id) references promotions (id);
alter table promotion_eligible_stores add constraint FKseynhh7707blt7b8qi69mns4b foreign key (promotion_id) references promotions (id);
alter table promotion_eligible_user_levels add constraint FK80bckqoln356j8kuu2ayqi4df foreign key (promotion_id) references promotions (id);
alter table reviews add constraint FKcgy7qjc1r99dp117y9en6lxye foreign key (user_id) references users (id);
alter table store_dishes add constraint FKl2mjj25rs79p74eqxi7a1139p foreign key (dish_id) references dishes (id);
alter table store_dishes add constraint FKx2dj7rusgqexxy5ujy68xga2 foreign key (store_id) references stores (id);
alter table store_highlight_tags add constraint FK18q6bs0tohhy1qe9ycmfhys76 foreign key (store_id) references stores (id);
alter table store_image_paths add constraint FKlx5to0bmnl17f1wxx1f6th6a2 foreign key (store_id) references stores (id);
alter table store_service_tags add constraint FKj6l271tpt1mopmxaesonjkhw3 foreign key (store_id) references stores (id);
alter table user_delivery_addresses add constraint FKi1yhotfihh3858knun6481ydy foreign key (user_id) references users (id);
alter table user_level_definitions add constraint FK3wwp1mr5isymolqs6urcqqdpw foreign key (store_id) references stores (id);
alter table user_notifications add constraint FK9f86wonnl11hos1cuf5fibutl foreign key (user_id) references users (id);
alter table user_sessions add constraint FK8klxsgb8dcjjklmqebqp1twd5 foreign key (user_id) references users (id);
alter table users add constraint FKtfjv69k61wo59y67hq3g67u1e foreign key (working_store_id) references stores (id);
