function createPlaceholderImage(label, background, color = "27402d") {
  return `https://placehold.co/1200x900/${background}/${color}?text=${encodeURIComponent(label)}`;
}

function createGallery(label, palette) {
  return palette.map((background, index) =>
    createPlaceholderImage(
      index === 0 ? `${label} Cover` : `${label} Library ${index}`,
      background,
    ),
  );
}

const storeLibraries = {
  nguyenHue: createGallery("Kamatcha Nguyen Hue", ["dbe8c8", "f1e7d7", "d4e0be"]),
  thuDuc: createGallery("Kamatcha Thu Duc", ["d9ead7", "edf2df", "dde7cf"]),
  thaoDien: createGallery("Kamatcha Thao Dien", ["d7eadc", "e8f0d2", "f3eadc"]),
  phuMyHung: createGallery("Kamatcha Phu My Hung", ["e5ebcf", "f4e6d8", "d6dfc4"]),
  tayHo: createGallery("Kamatcha Tay Ho", ["dce7d8", "efe3d1", "d0dcc2"]),
};

const categoryLibraries = {
  matcha: createGallery("Matcha Signature", ["d9ebc7", "cfe1ba", "f0e4d4"]),
  milkTea: createGallery("Milk Tea House", ["eadfcf", "dbe6c8", "d6d9c8"]),
  refreshers: createGallery("Tea and Fruit Refreshers", ["d6efe6", "eef5d4", "f0e6d5"]),
  dessert: createGallery("Bakery and Dessert", ["f2e4d6", "e2ebcf", "d7dcc7"]),
};

const itemLibraries = {
  matchaLatteCloud: createGallery("Matcha Latte Cloud", ["d7ecc0", "edf3d7", "f1e5d6"]),
  azukiMatcha: createGallery("Azuki Matcha", ["e1ebca", "f3e6d6", "d4e3c2"]),
  icedMatchaCoconut: createGallery("Iced Matcha Coconut", ["d5ede0", "e9f1d4", "efe6d8"]),
  roastedOolongMilkTea: createGallery("Roasted Oolong Milk Tea", ["eadcc9", "dce6c8", "e5e0cd"]),
  jasminePearlMilkTea: createGallery("Jasmine Pearl Milk Tea", ["e8dfcf", "d8ebcf", "efe8d7"]),
  brownSugarFreshMilk: createGallery("Brown Sugar Fresh Milk", ["e6d5c3", "f1e8d9", "dddcc9"]),
  peachOolongTea: createGallery("Peach Oolong Tea", ["f2dfd2", "def0d8", "ede7d7"]),
  yuzuGreenTea: createGallery("Yuzu Green Tea", ["e0f0cb", "d4ead8", "f0e5d3"]),
  mangoJasmineSparkling: createGallery("Mango Jasmine Sparkling", ["f1e2bf", "d9f0d8", "efe7d5"]),
  matchaRollCake: createGallery("Matcha Roll Cake", ["e8f0d1", "f2e1d4", "d6e2c6"]),
  butterCroissant: createGallery("Butter Croissant", ["f0dfc6", "eadfd3", "d8dcc4"]),
  tiramisuCup: createGallery("Tiramisu Cup", ["e8d9c7", "f0e6d8", "d5dcc8"]),
};

const eventLibraries = {
  greenMorning: createGallery("Green Morning Buy 1 Get 1", ["dff0cb", "edf4d7", "f1e4d6"]),
  matchaLab: createGallery("Workshop Matcha Lab", ["d6ecdc", "e9f1d5", "f0e4d3"]),
  acousticNight: createGallery("Acoustic Tea Night", ["e7decf", "d8e4c7", "eee6d8"]),
  memberDay: createGallery("Member Day", ["d9ebcf", "f2e5d6", "d8dec8"]),
};

export const navigationLinks = [
  { to: "/", label: "Home", end: true },
  { to: "/stores", label: "Stores" },
  { to: "/menu", label: "Menu" },
  { to: "/events", label: "Events" },
  { to: "/reviews", label: "Reviews" },
];

export const brandStats = [
  { value: "12", label: "signature stores across Ho Chi Minh City and Hanoi" },
  { value: "4.8/5", label: "guest satisfaction from weekly returning customers" },
  { value: "25k+", label: "drinks served every month for office and campus communities" },
];

export const brandPillars = [
  {
    title: "Urban tea spaces",
    description:
      "Wood interiors, tea-green tones, and warm lighting create the feel of a modern tea house.",
  },
  {
    title: "A menu built for repeat visits",
    description:
      "From signature matcha lattes to milk tea and pastries, the menu is designed to be easy to enjoy every day.",
  },
  {
    title: "Operations that scale smoothly",
    description:
      "This website is built to scale across ordering, promotions, memberships, and branch management.",
  },
];

export const signatureDrinks = [
  {
    name: "Matcha Latte Cloud",
    description: "Fine Uji matcha, fresh milk, and a light creamy foam layer.",
    accent: "Best seller",
  },
  {
    name: "Roasted Oolong Milk Tea",
    description: "Gently roasted oolong with a deep aroma and balanced sweetness for everyday drinking.",
    accent: "Afternoon favorite",
  },
  {
    name: "Coconut Matcha Espresso",
    description: "A bold mix of coconut, espresso, and matcha cream for guests who enjoy layered flavors.",
    accent: "Signature fusion",
  },
];

export const initialUsers = [
  {
    id: "user-minh-anh",
    name: "Minh Anh",
    email: "minh.anh@kamatcha.vn",
    role: "Customer",
    status: "Active",
    favoriteStoreId: "store-nguyen-hue",
  },
  {
    id: "user-quang-huy",
    name: "Quang Huy",
    email: "quang.huy@kamatcha.vn",
    role: "Customer",
    status: "Active",
    favoriteStoreId: "store-phu-my-hung",
  },
  {
    id: "user-bao-tran",
    name: "Bao Tran",
    email: "bao.tran@kamatcha.vn",
    role: "Customer",
    status: "Active",
    favoriteStoreId: "store-thu-duc",
  },
  {
    id: "user-thanh-nha",
    name: "Thanh Nha",
    email: "thanh.nha@kamatcha.vn",
    role: "Community lead",
    status: "Active",
    favoriteStoreId: "store-tay-ho",
  },
  {
    id: "user-linh-chi",
    name: "Linh Chi",
    email: "linh.chi@kamatcha.vn",
    role: "Customer",
    status: "Inactive",
    favoriteStoreId: "store-thu-duc",
  },
  {
    id: "user-khanh-duy",
    name: "Khanh Duy",
    email: "khanh.duy@kamatcha.vn",
    role: "Manager",
    status: "Active",
    favoriteStoreId: "store-thao-dien",
  },
  {
    id: "user-ngoc-han",
    name: "Ngoc Han",
    email: "ngoc.han@kamatcha.vn",
    role: "Customer",
    status: "Active",
    favoriteStoreId: "store-nguyen-hue",
  },
  {
    id: "user-tuan-kiet",
    name: "Tuan Kiet",
    email: "tuan.kiet@kamatcha.vn",
    role: "Customer",
    status: "Active",
    favoriteStoreId: "store-thu-duc",
  },
  {
    id: "user-phuong-linh",
    name: "Phuong Linh",
    email: "phuong.linh@kamatcha.vn",
    role: "Customer",
    status: "Active",
    favoriteStoreId: "store-thao-dien",
  },
];

export const initialStores = [
  {
    id: "store-nguyen-hue",
    name: "Kamatcha Nguyen Hue",
    area: "District 1, Ho Chi Minh City",
    address: "88 Nguyen Hue, Ben Nghe Ward",
    hours: "07:00 - 22:30",
    vibe: "A two-floor space that works well for meetings and focused work sessions.",
    description:
      "The flagship branch with an open frontage, bright wood finishes, and seating that looks out onto Nguyen Hue Walking Street.",
    specialty: "Matcha Latte Cloud",
    contactEmail: "nguyenhue@kamatcha.vn",
    phoneNumber: "0901 120 888",
    serviceTags: ["Flagship", "Premium", "Business meetings"],
    personality: "Polished, tidy, and ideal for hosting guests or meeting partners.",
    designSignature: "Light wood tones, warm lighting, and business-casual seating.",
    franchiseMood: "The model branch for Kamatcha's premium concept.",
    positionLabel: "Q1 business district",
    latitude: 10.7733,
    longitude: 106.7044,
    imagePaths: storeLibraries.nguyenHue,
  },
  {
    id: "store-thu-duc",
    name: "Kamatcha Thu Duc Campus",
    area: "Thu Duc, Ho Chi Minh City",
    address: "12 Vo Van Ngan, Linh Chieu Ward",
    hours: "07:00 - 22:30",
    vibe: "Bright, clean, and full of long tables for study groups and project work.",
    description:
      "A branch designed for students and young professionals, focused on a smart, calm atmosphere that supports studying and solo work.",
    specialty: "Roasted Oolong Milk Tea",
    contactEmail: "thuduc@kamatcha.vn",
    phoneNumber: "0901 254 668",
    serviceTags: ["Campus-friendly", "Study groups", "Plenty of outlets"],
    personality: "Young, thoughtful, and comfortable for long study sessions or independent work.",
    designSignature: "Long tables, supportive chairs, clean lighting, and small bookshelves.",
    franchiseMood: "A campus-friendly variation that still keeps Kamatcha's clean and calm brand DNA.",
    positionLabel: "Thu Duc campus hub",
    latitude: 10.8499,
    longitude: 106.7717,
    imagePaths: storeLibraries.thuDuc,
  },
  {
    id: "store-thao-dien",
    name: "Kamatcha Thao Dien",
    area: "Thao Dien, Thu Duc City",
    address: "21 Xuan Thuy, Thao Dien",
    hours: "07:00 - 22:00",
    vibe: "Soft, green, and filled with sunny balcony corners.",
    description:
      "A tea-garden-inspired space that works well for studying, working, and slow afternoon coffee dates.",
    specialty: "Yuzu Green Tea",
    contactEmail: "thaodien@kamatcha.vn",
    phoneNumber: "0901 330 221",
    serviceTags: ["Relaxed", "Tea garden", "Pet-friendly"],
    personality: "Welcoming, airy, and perfect for easy daytime meetups.",
    designSignature: "Plenty of greenery, wide glass windows, balconies, and natural textures.",
    franchiseMood: "Kamatcha's softest resort-meets-city expression.",
    positionLabel: "Thao Dien riverside",
    latitude: 10.8032,
    longitude: 106.7317,
    imagePaths: storeLibraries.thaoDien,
  },
  {
    id: "store-phu-my-hung",
    name: "Kamatcha Phu My Hung",
    area: "District 7, Ho Chi Minh City",
    address: "102 Nguyen Duc Canh, Tan Phong Ward",
    hours: "07:30 - 22:30",
    vibe: "Spacious and comfortable for friend groups and weekend family visits.",
    description:
      "A neighborhood and office-area branch with large seating zones for groups and families.",
    specialty: "Brown Sugar Fresh Milk",
    contactEmail: "phumyhung@kamatcha.vn",
    phoneNumber: "0901 441 772",
    serviceTags: ["Family-friendly", "Fast delivery", "Easy parking"],
    personality: "Steady, friendly, and convenient for families or larger groups.",
    designSignature: "A wide floor plan, generous circulation, and flexible seating sections.",
    franchiseMood: "A balanced dine-in and takeaway branch for residential neighborhoods.",
    positionLabel: "Phu My Hung family zone",
    latitude: 10.7289,
    longitude: 106.7218,
    imagePaths: storeLibraries.phuMyHung,
  },
  {
    id: "store-tay-ho",
    name: "Kamatcha Tay Ho",
    area: "Tay Ho, Ha Noi",
    address: "17 Dang Thai Mai, Quang An",
    hours: "07:00 - 22:30",
    vibe: "Open views that suit relaxed evenings and intimate workshops.",
    description:
      "A branch with wide window frames that works beautifully for small workshops and weekend acoustic nights.",
    specialty: "Jasmine Cheese Tea",
    contactEmail: "tayho@kamatcha.vn",
    phoneNumber: "0901 580 966",
    serviceTags: ["Workshops", "Acoustic nights", "Lake view"],
    personality: "Calm, relaxed, and ideal for small events or unhurried evenings.",
    designSignature: "Large window bays, warm evening lighting, and an open plan for community events.",
    franchiseMood: "A community tea lounge with a slower social rhythm.",
    positionLabel: "Tay Ho lake view",
    latitude: 21.0628,
    longitude: 105.8237,
    imagePaths: storeLibraries.tayHo,
  },
];

export const initialCategories = [
  {
    id: "category-matcha-signature",
    title: "Matcha Signature",
    description: "The signature line that defines the Kamatcha brand.",
    status: "Active",
    spotlight: "The hero range for first-time guests discovering the brand.",
    imagePaths: categoryLibraries.matcha,
  },
  {
    id: "category-milk-tea-house",
    title: "Milk Tea House",
    description: "Crowd-pleasing drinks that feel approachable for a wide range of guests.",
    status: "Active",
    spotlight: "A strong lunch-hour category with high repeat purchase among office guests.",
    imagePaths: categoryLibraries.milkTea,
  },
  {
    id: "category-refreshers",
    title: "Tea & Fruit Refreshers",
    description: "A cooling line designed for warm days and summer campaigns.",
    status: "Seasonal",
    spotlight: "Fresh, vibrant drinks that work especially well in promotional banners and delivery combos.",
    imagePaths: categoryLibraries.refreshers,
  },
  {
    id: "category-bakery-dessert",
    title: "Bakery & Dessert",
    description: "Add-on treats that increase basket value and enrich the dine-in experience.",
    status: "Active",
    spotlight: "Supports table combos, afternoon sets, and in-store upsell programs.",
    imagePaths: categoryLibraries.dessert,
  },
];

export const initialMenuItems = [
  {
    id: "item-matcha-latte-cloud",
    categoryId: "category-matcha-signature",
    name: "Matcha Latte Cloud",
    price: "65000",
    note: "silky milk foam",
    status: "Best seller",
    description: "A soft foam cap with smooth matcha flavor that is easy for new guests to love.",
    franchiseRequired: true,
    franchiseNote: "Required at every franchise branch to preserve Kamatcha's matcha identity.",
    orderCount: 3480,
    favoriteCount: 1320,
    availableStoreIds: [
      "store-nguyen-hue",
      "store-thu-duc",
      "store-thao-dien",
      "store-phu-my-hung",
      "store-tay-ho",
    ],
    stockByStoreId: {
      "store-nguyen-hue": 18,
      "store-thu-duc": 0,
      "store-thao-dien": 11,
      "store-phu-my-hung": 10,
      "store-tay-ho": 9,
    },
    imagePaths: itemLibraries.matchaLatteCloud,
  },
  {
    id: "item-azuki-matcha",
    categoryId: "category-matcha-signature",
    name: "Azuki Matcha",
    price: "69000",
    note: "lightly sweet red bean",
    status: "Active",
    description: "Red bean and matcha come together in a lightly sweet drink with satisfying texture.",
    orderCount: 1240,
    favoriteCount: 540,
    availableStoreIds: [
      "store-nguyen-hue",
      "store-thu-duc",
      "store-thao-dien",
      "store-tay-ho",
    ],
    stockByStoreId: {
      "store-nguyen-hue": 6,
      "store-thu-duc": 7,
      "store-thao-dien": 4,
      "store-tay-ho": 5,
    },
    imagePaths: itemLibraries.azukiMatcha,
  },
  {
    id: "item-iced-matcha-coconut",
    categoryId: "category-matcha-signature",
    name: "Iced Matcha Coconut",
    price: "72000",
    note: "fresh coconut and matcha",
    status: "Active",
    description: "A tropical-style signature that fits summer campaigns and seasonal feature menus.",
    orderCount: 970,
    favoriteCount: 430,
    availableStoreIds: [
      "store-nguyen-hue",
      "store-thao-dien",
      "store-phu-my-hung",
    ],
    stockByStoreId: {
      "store-nguyen-hue": 0,
      "store-thao-dien": 3,
      "store-phu-my-hung": 2,
    },
    imagePaths: itemLibraries.icedMatchaCoconut,
  },
  {
    id: "item-roasted-oolong-milk-tea",
    categoryId: "category-milk-tea-house",
    name: "Roasted Oolong Milk Tea",
    price: "58000",
    note: "deep tea profile",
    status: "Best seller",
    description: "Strong tea character, moderate sweetness, and a profile that office guests can order every day.",
    franchiseRequired: true,
    franchiseNote: "A core menu item to anchor repeat everyday purchases at every branch.",
    orderCount: 3260,
    favoriteCount: 1180,
    availableStoreIds: [
      "store-nguyen-hue",
      "store-thu-duc",
      "store-thao-dien",
      "store-phu-my-hung",
      "store-tay-ho",
    ],
    stockByStoreId: {
      "store-nguyen-hue": 20,
      "store-thu-duc": 18,
      "store-thao-dien": 12,
      "store-phu-my-hung": 14,
      "store-tay-ho": 10,
    },
    imagePaths: itemLibraries.roastedOolongMilkTea,
  },
  {
    id: "item-jasmine-pearl-milk-tea",
    categoryId: "category-milk-tea-house",
    name: "Jasmine Pearl Milk Tea",
    price: "55000",
    note: "soft pearls",
    status: "Active",
    description: "A gentle floral profile with soft pearls that pairs naturally with in-store snacks.",
    orderCount: 2080,
    favoriteCount: 760,
    availableStoreIds: [
      "store-nguyen-hue",
      "store-thu-duc",
      "store-phu-my-hung",
      "store-tay-ho",
    ],
    stockByStoreId: {
      "store-nguyen-hue": 8,
      "store-thu-duc": 6,
      "store-phu-my-hung": 7,
      "store-tay-ho": 4,
    },
    imagePaths: itemLibraries.jasminePearlMilkTea,
  },
  {
    id: "item-brown-sugar-fresh-milk",
    categoryId: "category-milk-tea-house",
    name: "Brown Sugar Fresh Milk",
    price: "60000",
    note: "rich fresh milk",
    status: "Active",
    description: "A recognizable takeaway favorite with a strong visual identity on social media.",
    franchiseRequired: true,
    franchiseNote: "A required part of the franchise takeaway lineup and visual identity.",
    orderCount: 2990,
    favoriteCount: 990,
    availableStoreIds: [
      "store-nguyen-hue",
      "store-thu-duc",
      "store-thao-dien",
      "store-phu-my-hung",
      "store-tay-ho",
    ],
    stockByStoreId: {
      "store-nguyen-hue": 13,
      "store-thu-duc": 11,
      "store-thao-dien": 5,
      "store-phu-my-hung": 16,
      "store-tay-ho": 8,
    },
    imagePaths: itemLibraries.brownSugarFreshMilk,
  },
  {
    id: "item-peach-oolong-tea",
    categoryId: "category-refreshers",
    name: "Peach Oolong Tea",
    price: "52000",
    note: "crisp yellow peach",
    status: "Seasonal",
    description: "A refreshing tea with crisp peach notes that works well in lunch and summer combos.",
    orderCount: 1890,
    favoriteCount: 650,
    availableStoreIds: [
      "store-thu-duc",
      "store-thao-dien",
      "store-phu-my-hung",
    ],
    stockByStoreId: {
      "store-thu-duc": 7,
      "store-thao-dien": 9,
      "store-phu-my-hung": 6,
    },
    imagePaths: itemLibraries.peachOolongTea,
  },
  {
    id: "item-yuzu-green-tea",
    categoryId: "category-refreshers",
    name: "Yuzu Green Tea",
    price: "59000",
    note: "bright citrus aroma",
    status: "Active",
    description: "Clear yuzu brightness with a clean finish for guests who prefer lighter, less sweet drinks.",
    franchiseRequired: true,
    franchiseNote: "A required refresher to keep the menu fresh, balanced, and easy to drink.",
    orderCount: 2760,
    favoriteCount: 1105,
    availableStoreIds: [
      "store-nguyen-hue",
      "store-thu-duc",
      "store-thao-dien",
      "store-phu-my-hung",
      "store-tay-ho",
    ],
    stockByStoreId: {
      "store-nguyen-hue": 15,
      "store-thu-duc": 13,
      "store-thao-dien": 12,
      "store-phu-my-hung": 10,
      "store-tay-ho": 7,
    },
    imagePaths: itemLibraries.yuzuGreenTea,
  },
  {
    id: "item-mango-jasmine-sparkling",
    categoryId: "category-refreshers",
    name: "Mango Jasmine Sparkling",
    price: "62000",
    note: "light sparkle",
    status: "Active",
    description: "A lightly sparkling drink with a playful look that performs well in summer campaigns.",
    orderCount: 1430,
    favoriteCount: 590,
    availableStoreIds: [
      "store-nguyen-hue",
      "store-thao-dien",
      "store-phu-my-hung",
    ],
    stockByStoreId: {
      "store-nguyen-hue": 5,
      "store-thao-dien": 4,
      "store-phu-my-hung": 0,
    },
    imagePaths: itemLibraries.mangoJasmineSparkling,
  },
  {
    id: "item-matcha-roll-cake",
    categoryId: "category-bakery-dessert",
    name: "Matcha Roll Cake",
    price: "42000",
    note: "soft matcha sponge",
    status: "Active",
    description: "An easy dessert pairing for hot drinks and afternoon set menus.",
    orderCount: 920,
    favoriteCount: 340,
    availableStoreIds: [
      "store-nguyen-hue",
      "store-thu-duc",
      "store-tay-ho",
    ],
    stockByStoreId: {
      "store-nguyen-hue": 5,
      "store-thu-duc": 4,
      "store-tay-ho": 3,
    },
    imagePaths: itemLibraries.matchaRollCake,
  },
  {
    id: "item-butter-croissant",
    categoryId: "category-bakery-dessert",
    name: "Butter Croissant",
    price: "35000",
    note: "baked fresh each morning",
    status: "Active",
    description: "A familiar bakery staple that works well for breakfast sales and quick counter combos.",
    orderCount: 1620,
    favoriteCount: 470,
    availableStoreIds: [
      "store-nguyen-hue",
      "store-thu-duc",
      "store-thao-dien",
      "store-phu-my-hung",
      "store-tay-ho",
    ],
    stockByStoreId: {
      "store-nguyen-hue": 12,
      "store-thu-duc": 9,
      "store-thao-dien": 8,
      "store-phu-my-hung": 10,
      "store-tay-ho": 7,
    },
    imagePaths: itemLibraries.butterCroissant,
  },
  {
    id: "item-tiramisu-cup",
    categoryId: "category-bakery-dessert",
    name: "Tiramisu Cup",
    price: "48000",
    note: "light coffee finish",
    status: "Active",
    description: "A soft dessert with balanced richness that pairs nicely with oolong or matcha.",
    orderCount: 880,
    favoriteCount: 315,
    availableStoreIds: [
      "store-nguyen-hue",
      "store-thao-dien",
      "store-phu-my-hung",
      "store-tay-ho",
    ],
    stockByStoreId: {
      "store-nguyen-hue": 0,
      "store-thao-dien": 0,
      "store-phu-my-hung": 0,
      "store-tay-ho": 0,
    },
    imagePaths: itemLibraries.tiramisuCup,
  },
];

export const initialEvents = [
  {
    id: "event-green-morning",
    storeId: "store-nguyen-hue",
    title: "Green Morning Buy 1 Get 1",
    schedule: "Monday and Thursday | 07:00 - 10:00",
    startsAt: "2026-03-23T07:00:00+07:00",
    endsAt: "2026-03-23T10:00:00+07:00",
    location: "All Kamatcha branches",
    summary:
      "A morning promotion on the Matcha Signature line designed to attract early office traffic.",
    capacity: 120,
    bookedCount: 76,
    featuredItemIds: ["item-matcha-latte-cloud", "item-yuzu-green-tea"],
    imagePaths: eventLibraries.greenMorning,
  },
  {
    id: "event-matcha-lab",
    storeId: "store-tay-ho",
    title: "Workshop Matcha Lab",
    schedule: "Second Sunday of every month | 15:00",
    startsAt: "2026-04-12T15:00:00+07:00",
    endsAt: "2026-04-12T17:00:00+07:00",
    location: "Kamatcha Tay Ho",
    summary:
      "Guests experience ceremonial matcha whisking and explore different brewing styles.",
    capacity: 24,
    bookedCount: 24,
    featuredItemIds: ["item-azuki-matcha", "item-matcha-roll-cake"],
    imagePaths: eventLibraries.matchaLab,
  },
  {
    id: "event-acoustic-night",
    storeId: "store-nguyen-hue",
    title: "Acoustic Tea Night",
    schedule: "Every Friday | 19:30",
    startsAt: "2026-03-27T19:30:00+07:00",
    endsAt: "2026-03-27T21:30:00+07:00",
    location: "Kamatcha Nguyen Hue",
    summary:
      "An intimate music night for younger groups, paired with drink and dessert combos.",
    capacity: 60,
    bookedCount: 41,
    featuredItemIds: ["item-brown-sugar-fresh-milk", "item-tiramisu-cup"],
    imagePaths: eventLibraries.acousticNight,
  },
  {
    id: "event-member-day",
    storeId: "store-phu-my-hung",
    title: "Member Day",
    schedule: "The 15th of every month",
    startsAt: "2026-04-15T09:00:00+07:00",
    endsAt: "2026-04-15T22:00:00+07:00",
    location: "Online and in-store",
    summary:
      "Double loyalty points and a 15% perk for members with registered accounts.",
    capacity: 180,
    bookedCount: 180,
    featuredItemIds: ["item-brown-sugar-fresh-milk", "item-peach-oolong-tea"],
    imagePaths: eventLibraries.memberDay,
  },
];

export const initialReviews = [
  {
    id: "review-001",
    userId: "user-minh-anh",
    targetType: "item",
    targetId: "item-matcha-latte-cloud",
    rating: "4.9",
    title: "A truly memorable signature drink",
    comment:
      "The matcha flavor is bold but still very approachable, and it feels perfect for casual catchups and social content.",
    createdAt: "2026-03-03",
  },
  {
    id: "review-002",
    userId: "user-quang-huy",
    targetType: "item",
    targetId: "item-roasted-oolong-milk-tea",
    rating: "4.8",
    title: "Great for a daily takeaway run",
    comment:
      "The roasted oolong is rich, not too sweet, and ideal for grabbing before work starts.",
    createdAt: "2026-03-06",
  },
  {
    id: "review-003",
    userId: "user-bao-tran",
    targetType: "store",
    targetId: "store-thao-dien",
    rating: "4.7",
    title: "The atmosphere is so calming",
    comment:
      "The Thao Dien branch has lots of greenery, works well for studying, and the staff are lovely.",
    createdAt: "2026-03-08",
  },
  {
    id: "review-004",
    userId: "user-thanh-nha",
    targetType: "event",
    targetId: "event-acoustic-night",
    rating: "4.9",
    title: "A perfectly balanced music night",
    comment:
      "The acoustic night had a great atmosphere, the music volume felt right, and the dessert combo was spot on.",
    createdAt: "2026-03-09",
  },
  {
    id: "review-005",
    userId: "user-linh-chi",
    targetType: "category",
    targetId: "category-bakery-dessert",
    rating: "4.6",
    title: "Desserts that upsell naturally",
    comment:
      "The pastry range feels varied, affordable, and easy to pair with milk tea orders.",
    createdAt: "2026-03-11",
  },
  {
    id: "review-006",
    userId: "user-khanh-duy",
    targetType: "store",
    targetId: "store-nguyen-hue",
    rating: "4.8",
    title: "Great for meetings and group seating",
    comment:
      "The space looks polished, works well for hosting, and has flexible seating for team meetings.",
    createdAt: "2026-03-12",
  },
  {
    id: "review-007",
    userId: "user-minh-anh",
    targetType: "event",
    targetId: "event-matcha-lab",
    rating: "5.0",
    title: "A workshop with real depth",
    comment:
      "The workshop was fun, highly shareable, and genuinely helped guests understand matcha better.",
    createdAt: "2026-03-15",
  },
  {
    id: "review-008",
    userId: "user-quang-huy",
    targetType: "category",
    targetId: "category-milk-tea-house",
    rating: "4.7",
    title: "An easy category for new guests",
    comment:
      "The milk tea range feels approachable and sells well to office guests and first-timers.",
    createdAt: "2026-03-16",
  },
  {
    id: "review-009",
    userId: "user-bao-tran",
    targetType: "store",
    targetId: "store-thu-duc",
    rating: "4.8",
    title: "Excellent for studying",
    comment:
      "The Thu Duc branch is bright, clean, and comfortable for long study sessions with a campus feel.",
    createdAt: "2026-03-17",
  },
  {
    id: "review-010",
    userId: "user-linh-chi",
    targetType: "store",
    targetId: "store-phu-my-hung",
    rating: "4.7",
    title: "A nice place to visit with family",
    comment:
      "The Phu My Hung store is spacious, airy, and still serves quickly on weekends.",
    createdAt: "2026-03-18",
  },
  {
    id: "review-011",
    userId: "user-minh-anh",
    targetType: "item",
    targetId: "item-brown-sugar-fresh-milk",
    rating: "4.7",
    title: "A very solid takeaway drink",
    comment:
      "The brown sugar layers look great, the flavor is familiar, and it is easy to recommend to new guests.",
    createdAt: "2026-03-18",
  },
  {
    id: "review-012",
    userId: "user-quang-huy",
    targetType: "item",
    targetId: "item-yuzu-green-tea",
    rating: "4.9",
    title: "A refresher that is incredibly easy to enjoy",
    comment:
      "The yuzu note is distinct, the finish is clean, and it feels like a must-have at every Kamatcha branch.",
    createdAt: "2026-03-19",
  },
  {
    id: "review-013",
    userId: "user-thanh-nha",
    targetType: "event",
    targetId: "event-member-day",
    rating: "4.8",
    title: "A very sensible member program",
    comment:
      "Member Day does a great job encouraging repeat visits and pairing perks with core menu items.",
    createdAt: "2026-03-19",
  },
  {
    id: "review-014",
    userId: "user-ngoc-han",
    targetType: "item",
    targetId: "item-matcha-latte-cloud",
    rating: "4.8",
    title: "Silky foam and very photogenic",
    comment:
      "This drink looks beautiful in the cup, tastes light, and fits perfectly for meetups at Nguyen Hue.",
    createdAt: "2026-03-19",
  },
  {
    id: "review-015",
    userId: "user-tuan-kiet",
    targetType: "item",
    targetId: "item-roasted-oolong-milk-tea",
    rating: "4.7",
    title: "Bold tea that helps me focus",
    comment:
      "I often get this at Thu Duc when I need to study for hours because it tastes full-bodied without becoming too sweet.",
    createdAt: "2026-03-20",
  },
  {
    id: "review-016",
    userId: "user-phuong-linh",
    targetType: "item",
    targetId: "item-brown-sugar-fresh-milk",
    rating: "4.6",
    title: "A classic takeaway favorite",
    comment:
      "I usually order it on the way to work because it looks great, tastes familiar, and is easy to recommend to friends.",
    createdAt: "2026-03-20",
  },
  {
    id: "review-017",
    userId: "user-ngoc-han",
    targetType: "item",
    targetId: "item-yuzu-green-tea",
    rating: "4.8",
    title: "Clean, bright, and refreshing",
    comment:
      "Yuzu Green Tea feels very clean on the palate and is perfect for sunny days in greenery-filled spaces.",
    createdAt: "2026-03-20",
  },
  {
    id: "review-018",
    userId: "user-minh-anh",
    targetType: "item",
    targetId: "item-azuki-matcha",
    rating: "4.7",
    title: "Fun texture and easy to remember",
    comment:
      "The azuki pairs beautifully with matcha and makes the drink feel more premium than standard menu items.",
    createdAt: "2026-03-20",
  },
  {
    id: "review-019",
    userId: "user-bao-tran",
    targetType: "item",
    targetId: "item-jasmine-pearl-milk-tea",
    rating: "4.6",
    title: "Very approachable for a group of friends",
    comment:
      "The pearls are soft and the floral profile is light enough that everyone in the group can agree on it.",
    createdAt: "2026-03-20",
  },
  {
    id: "review-020",
    userId: "user-linh-chi",
    targetType: "item",
    targetId: "item-peach-oolong-tea",
    rating: "4.5",
    title: "Refreshing peach tea",
    comment:
      "This is perfect for lunch because the peach note stands out and it pairs easily with pastries.",
    createdAt: "2026-03-20",
  },
  {
    id: "review-021",
    userId: "user-tuan-kiet",
    targetType: "store",
    targetId: "store-nguyen-hue",
    rating: "4.9",
    title: "A flagship that really earns the title",
    comment:
      "The business-casual atmosphere is excellent, and it feels professional whether you are hosting or working solo.",
    createdAt: "2026-03-20",
  },
  {
    id: "review-022",
    userId: "user-phuong-linh",
    targetType: "store",
    targetId: "store-thao-dien",
    rating: "4.8",
    title: "Airy and genuinely charming",
    comment:
      "I love the open layout, the greenery, and the natural light at the Thao Dien branch.",
    createdAt: "2026-03-20",
  },
  {
    id: "review-023",
    userId: "user-ngoc-han",
    targetType: "store",
    targetId: "store-thu-duc",
    rating: "4.7",
    title: "Great for studying or meeting friends",
    comment:
      "The long tables, plenty of power outlets, and comfortable sound level make it great for both study groups and work.",
    createdAt: "2026-03-20",
  },
  {
    id: "review-024",
    userId: "user-bao-tran",
    targetType: "store",
    targetId: "store-nguyen-hue",
    rating: "4.8",
    title: "Elegant but still relaxed",
    comment:
      "The store feels premium without becoming distant, and the evening lighting is perfect for longer stays.",
    createdAt: "2026-03-20",
  },
  {
    id: "review-025",
    userId: "user-minh-anh",
    targetType: "store",
    targetId: "store-thu-duc",
    rating: "4.9",
    title: "Clean and unmistakably Kamatcha",
    comment:
      "The Thu Duc branch keeps the clean, calm Kamatcha DNA with friendly staff and consistently strong core drinks.",
    createdAt: "2026-03-20",
  },
];

export const loginBenefits = [
  "Manage membership details and branch-specific perks.",
  "Track revenue, shifts, and best-selling menu items for the day.",
  "Update events, seasonal bundles, and customer feedback.",
];

