spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.hbm2ddl.delimiter=;
spring.jpa.properties.jakarta.persistence.schema-generation.create-source=metadata
spring.jpa.properties.jakarta.persistence.schema-generation.database.action=none
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=database/schema-mysql.sql

spring.main.web-application-type=none
spring.main.lazy-initialization=true

app.openai.enabled=false
app.payos.enabled=false
