function createPlaceholderImage(label, background, color = "27402d") {
  return `https://placehold.co/1200x900/${background}/${color}?text=${encodeURIComponent(label)}`;
}

function createGallery(label, palette) {
  return palette.map((background, index) =>
    createPlaceholderImage(
      index === 0 ? `${label} Cover` : `${label} Library ${index}`,
      background,
    ),
  );
}

const storeLibraries = {
  nguyenHue: createGallery("Tea Matcha Nguyen Hue", ["dbe8c8", "f1e7d7", "d4e0be"]),
  thuDuc: createGallery("Tea Matcha Thu Duc", ["d9ead7", "edf2df", "dde7cf"]),
  thaoDien: createGallery("Tea Matcha Thao Dien", ["d7eadc", "e8f0d2", "f3eadc"]),
  phuMyHung: createGallery("Tea Matcha Phu My Hung", ["e5ebcf", "f4e6d8", "d6dfc4"]),
  tayHo: createGallery("Tea Matcha Tay Ho", ["dce7d8", "efe3d1", "d0dcc2"]),
};

const categoryLibraries = {
  matcha: createGallery("Matcha Signature", ["d9ebc7", "cfe1ba", "f0e4d4"]),
  milkTea: createGallery("Milk Tea House", ["eadfcf", "dbe6c8", "d6d9c8"]),
  refreshers: createGallery("Tea and Fruit Refreshers", ["d6efe6", "eef5d4", "f0e6d5"]),
  dessert: createGallery("Bakery and Dessert", ["f2e4d6", "e2ebcf", "d7dcc7"]),
};

const itemLibraries = {
  matchaLatteCloud: createGallery("Matcha Latte Cloud", ["d7ecc0", "edf3d7", "f1e5d6"]),
  azukiMatcha: createGallery("Azuki Matcha", ["e1ebca", "f3e6d6", "d4e3c2"]),
  icedMatchaCoconut: createGallery("Iced Matcha Coconut", ["d5ede0", "e9f1d4", "efe6d8"]),
  roastedOolongMilkTea: createGallery("Roasted Oolong Milk Tea", ["eadcc9", "dce6c8", "e5e0cd"]),
  jasminePearlMilkTea: createGallery("Jasmine Pearl Milk Tea", ["e8dfcf", "d8ebcf", "efe8d7"]),
  brownSugarFreshMilk: createGallery("Brown Sugar Fresh Milk", ["e6d5c3", "f1e8d9", "dddcc9"]),
  peachOolongTea: createGallery("Peach Oolong Tea", ["f2dfd2", "def0d8", "ede7d7"]),
  yuzuGreenTea: createGallery("Yuzu Green Tea", ["e0f0cb", "d4ead8", "f0e5d3"]),
  mangoJasmineSparkling: createGallery("Mango Jasmine Sparkling", ["f1e2bf", "d9f0d8", "efe7d5"]),
  matchaRollCake: createGallery("Matcha Roll Cake", ["e8f0d1", "f2e1d4", "d6e2c6"]),
  butterCroissant: createGallery("Butter Croissant", ["f0dfc6", "eadfd3", "d8dcc4"]),
  tiramisuCup: createGallery("Tiramisu Cup", ["e8d9c7", "f0e6d8", "d5dcc8"]),
};

const eventLibraries = {
  greenMorning: createGallery("Green Morning Buy 1 Get 1", ["dff0cb", "edf4d7", "f1e4d6"]),
  matchaLab: createGallery("Workshop Matcha Lab", ["d6ecdc", "e9f1d5", "f0e4d3"]),
  acousticNight: createGallery("Acoustic Tea Night", ["e7decf", "d8e4c7", "eee6d8"]),
  memberDay: createGallery("Member Day", ["d9ebcf", "f2e5d6", "d8dec8"]),
};

export const navigationLinks = [
  { to: "/", label: "Home", end: true },
  { to: "/stores", label: "Cửa hàng" },
  { to: "/menu", label: "Thực đơn" },
  { to: "/events", label: "Sự kiện" },
  { to: "/reviews", label: "Đánh giá" },
];

export const brandStats = [
  { value: "12", label: "cua hang signature tai TP.HCM va Ha Noi" },
  { value: "4.8/5", label: "diem yeu thich tu khach hang quay lai hang tuan" },
  { value: "25k+", label: "ly nuoc phuc vu moi thang cho gioi tre van phong" },
];

export const brandPillars = [
  {
    title: "Khong gian thanh thi",
    description:
      "Noi that go, tong xanh tra va anh sang am tao cam giac giong mot tea house hien dai.",
  },
  {
    title: "Menu de gan",
    description:
      "Tu matcha latte signature den milk tea va banh ngan, menu duoc thiet ke de de uong moi ngay.",
  },
  {
    title: "Van hanh mem mai",
    description:
      "Website nay co the mo rong cho dat mon, khuyen mai, thanh vien va quan ly chi nhanh.",
  },
];

export const signatureDrinks = [
  {
    name: "Matcha Latte Cloud",
    description: "Matcha Uji danh bot min, sua tuoi va lop foam beo nhe.",
    accent: "Best seller",
  },
  {
    name: "Roasted Oolong Milk Tea",
    description: "Tra oolong rang nhe, huong thom sau va it ngot de uong hang ngay.",
    accent: "Afternoon pick",
  },
  {
    name: "Coconut Matcha Espresso",
    description: "Ket hop dua, espresso va kem matcha cho khach thich vi la.",
    accent: "Signature fusion",
  },
];

export const initialUsers = [
  {
    id: "user-minh-anh",
    name: "Minh Anh",
    email: "minh.anh@teamatcha.vn",
    role: "Customer",
    status: "Active",
    favoriteStoreId: "store-nguyen-hue",
  },
  {
    id: "user-quang-huy",
    name: "Quang Huy",
    email: "quang.huy@teamatcha.vn",
    role: "Customer",
    status: "Active",
    favoriteStoreId: "store-phu-my-hung",
  },
  {
    id: "user-bao-tran",
    name: "Bao Tran",
    email: "bao.tran@teamatcha.vn",
    role: "Customer",
    status: "Active",
    favoriteStoreId: "store-thu-duc",
  },
  {
    id: "user-thanh-nha",
    name: "Thanh Nha",
    email: "thanh.nha@teamatcha.vn",
    role: "Community lead",
    status: "Active",
    favoriteStoreId: "store-tay-ho",
  },
  {
    id: "user-linh-chi",
    name: "Linh Chi",
    email: "linh.chi@teamatcha.vn",
    role: "Customer",
    status: "Inactive",
    favoriteStoreId: "store-thu-duc",
  },
  {
    id: "user-khanh-duy",
    name: "Khanh Duy",
    email: "khanh.duy@teamatcha.vn",
    role: "Manager",
    status: "Active",
    favoriteStoreId: "store-thao-dien",
  },
  {
    id: "user-ngoc-han",
    name: "Ngoc Han",
    email: "ngoc.han@teamatcha.vn",
    role: "Customer",
    status: "Active",
    favoriteStoreId: "store-nguyen-hue",
  },
  {
    id: "user-tuan-kiet",
    name: "Tuan Kiet",
    email: "tuan.kiet@teamatcha.vn",
    role: "Customer",
    status: "Active",
    favoriteStoreId: "store-thu-duc",
  },
  {
    id: "user-phuong-linh",
    name: "Phuong Linh",
    email: "phuong.linh@teamatcha.vn",
    role: "Customer",
    status: "Active",
    favoriteStoreId: "store-thao-dien",
  },
];

export const initialStores = [
  {
    id: "store-nguyen-hue",
    name: "Tea Matcha Nguyen Hue",
    area: "Quan 1, TP.HCM",
    address: "88 Nguyen Hue, Ben Nghe",
    hours: "07:00 - 22:30",
    vibe: "Khong gian 2 tang phu hop hop mat va ngoi lam viec.",
    description:
      "Chi nhanh flagship voi mat tien mo rong, tone go sang va goc ngoi nhin ra pho di bo Nguyen Hue.",
    specialty: "Matcha Latte Cloud",
    contactEmail: "nguyenhue@teamatcha.vn",
    phoneNumber: "0901 120 888",
    serviceTags: ["Flagship", "Sang trong", "Tiep khach"],
    personality: "Sang trong, gon gang va phu hop tiep khach hoac gap doi tac.",
    designSignature: "Tong mau go sang, anh den am va seating business-casual.",
    franchiseMood: "Chi nhanh hinh mau cho concept premium cua Tea Matcha.",
    positionLabel: "Q1 business district",
    latitude: 10.7733,
    longitude: 106.7044,
    imagePaths: storeLibraries.nguyenHue,
  },
  {
    id: "store-thu-duc",
    name: "Tea Matcha Thu Duc Campus",
    area: "Thu Duc, TP.HCM",
    address: "12 Vo Van Ngan, Linh Chieu",
    hours: "07:00 - 22:30",
    vibe: "Sach se, sang ro, nhieu ban dai cho hoc nhom va lam bai.",
    description:
      "Chi nhanh danh cho nhom sinh vien va nguoi di lam tre, tap trung vao cam giac tri thuc, yen tinh va de hoc tap.",
    specialty: "Roasted Oolong Milk Tea",
    contactEmail: "thuduc@teamatcha.vn",
    phoneNumber: "0901 254 668",
    serviceTags: ["Sinh vien tri thuc", "Hoc nhom", "Socket day du"],
    personality: "Tre, tri thuc va de ngoi lau cho hoc bai hoac lam viec ca nhan.",
    designSignature: "Ban dai, ghe tua thoai mai, anh sang sach va ke sach nho.",
    franchiseMood: "Bien the campus-friendly nhung van giu DNA sach se, chill cua thuong hieu.",
    positionLabel: "Thu Duc campus hub",
    latitude: 10.8499,
    longitude: 106.7717,
    imagePaths: storeLibraries.thuDuc,
  },
  {
    id: "store-thao-dien",
    name: "Tea Matcha Thao Dien",
    area: "Thao Dien, TP. Thu Duc",
    address: "21 Xuan Thuy, Thao Dien",
    hours: "07:00 - 22:00",
    vibe: "Nhe nha, nhieu cay xanh va goc ban cong don nang.",
    description:
      "Khong gian mang chat tea garden, phu hop hoc bai, ngoi lam viec va hen cafe cuoi chieu.",
    specialty: "Yuzu Green Tea",
    contactEmail: "thaodien@teamatcha.vn",
    phoneNumber: "0901 330 221",
    serviceTags: ["Mat me than thien", "Tea garden", "Pet friendly"],
    personality: "Than thien, thoang mat va hop nhung buoi gap go nhe nha ban ngay.",
    designSignature: "Nhieu cay xanh, cua kinh rong, ban cong va chat lieu moc tu nhien.",
    franchiseMood: "Bien the resort-urban mem mai nhat cua Tea Matcha.",
    positionLabel: "Thao Dien riverside",
    latitude: 10.8032,
    longitude: 106.7317,
    imagePaths: storeLibraries.thaoDien,
  },
  {
    id: "store-phu-my-hung",
    name: "Tea Matcha Phu My Hung",
    area: "Quan 7, TP.HCM",
    address: "102 Nguyen Duc Canh, Tan Phong",
    hours: "07:30 - 22:30",
    vibe: "Rong rai cho nhom ban va gia dinh cuoi tuan.",
    description:
      "Chi nhanh phuc vu khu dan cu va van phong, co khu seating lon cho nhom va gia dinh.",
    specialty: "Brown Sugar Fresh Milk",
    contactEmail: "phumyhung@teamatcha.vn",
    phoneNumber: "0901 441 772",
    serviceTags: ["Gia dinh", "Giao hang nhanh", "Parking de"],
    personality: "On dinh, than thien va thuan tien cho gia dinh hoac nhom dong nguoi.",
    designSignature: "Mat bang rong, luong di chuyen thoang va khu seating linh hoat.",
    franchiseMood: "Diem can bang giua dine-in va take-away cho khu dan cu.",
    positionLabel: "Phu My Hung family zone",
    latitude: 10.7289,
    longitude: 106.7218,
    imagePaths: storeLibraries.phuMyHung,
  },
  {
    id: "store-tay-ho",
    name: "Tea Matcha Tay Ho",
    area: "Tay Ho, Ha Noi",
    address: "17 Dang Thai Mai, Quang An",
    hours: "07:00 - 22:30",
    vibe: "View thong thoang, phu hop chill toi va workshop nho.",
    description:
      "Chi nhanh co nhieu khung cua rong, hop cac buoi workshop nho va dem acoustic cuoi tuan.",
    specialty: "Jasmine Cheese Tea",
    contactEmail: "tayho@teamatcha.vn",
    phoneNumber: "0901 580 966",
    serviceTags: ["Workshop", "Acoustic", "View song"],
    personality: "Lang, chill va hop cho workshop nho hay buoi toi thu gian.",
    designSignature: "Khung cua rong, dem den am va layout mo de to chuc su kien nho.",
    franchiseMood: "Diem hen cong dong theo phong cach tea lounge.",
    positionLabel: "Tay Ho lake view",
    latitude: 21.0628,
    longitude: 105.8237,
    imagePaths: storeLibraries.tayHo,
  },
];

export const initialCategories = [
  {
    id: "category-matcha-signature",
    title: "Matcha Signature",
    description: "Nhom mon giup dinh hinh thuong hieu Tea Matcha.",
    status: "Active",
    spotlight: "Dong mon nhan dien thuong hieu, phu hop cho khach moi ghe quan lan dau.",
    imagePaths: categoryLibraries.matcha,
  },
  {
    id: "category-milk-tea-house",
    title: "Milk Tea House",
    description: "Cac mon quoc dan de tiep can voi nhieu doi tuong khach.",
    status: "Active",
    spotlight: "Phu hop gio trua va tan so mua lap lai cao trong nhom van phong.",
    imagePaths: categoryLibraries.milkTea,
  },
  {
    id: "category-refreshers",
    title: "Tea & Fruit Refreshers",
    description: "Dong nuoc mat, hop ngay nang nong va mua he.",
    status: "Seasonal",
    spotlight: "Nhom mon thanh mat, de day tren banner khuyen mai va combo giao nhanh.",
    imagePaths: categoryLibraries.refreshers,
  },
  {
    id: "category-bakery-dessert",
    title: "Bakery & Dessert",
    description: "Mon an kem de tang gia tri hoa don va trai nghiem tai quan.",
    status: "Active",
    spotlight: "Ho tro combo tai ban, afternoon set va cac chuong trinh upsell tai quan.",
    imagePaths: categoryLibraries.dessert,
  },
];

export const initialMenuItems = [
  {
    id: "item-matcha-latte-cloud",
    categoryId: "category-matcha-signature",
    name: "Matcha Latte Cloud",
    price: "65000",
    note: "foam sua min",
    status: "Best seller",
    description: "Lop foam day nhe, vi matcha min va de tiep can voi khach moi.",
    franchiseRequired: true,
    franchiseNote: "Mon bat buoc tai moi cua hang nhuong quyen de giu nhan dien matcha.",
    orderCount: 3480,
    favoriteCount: 1320,
    availableStoreIds: [
      "store-nguyen-hue",
      "store-thu-duc",
      "store-thao-dien",
      "store-phu-my-hung",
      "store-tay-ho",
    ],
    stockByStoreId: {
      "store-nguyen-hue": 18,
      "store-thu-duc": 0,
      "store-thao-dien": 11,
      "store-phu-my-hung": 10,
      "store-tay-ho": 9,
    },
    imagePaths: itemLibraries.matchaLatteCloud,
  },
  {
    id: "item-azuki-matcha",
    categoryId: "category-matcha-signature",
    name: "Azuki Matcha",
    price: "69000",
    note: "dau do ngot nhe",
    status: "Active",
    description: "Ket hop dau do va matcha tao vi ngot nhe, hop cho khach thich texture.",
    orderCount: 1240,
    favoriteCount: 540,
    availableStoreIds: [
      "store-nguyen-hue",
      "store-thu-duc",
      "store-thao-dien",
      "store-tay-ho",
    ],
    stockByStoreId: {
      "store-nguyen-hue": 6,
      "store-thu-duc": 7,
      "store-thao-dien": 4,
      "store-tay-ho": 5,
    },
    imagePaths: itemLibraries.azukiMatcha,
  },
  {
    id: "item-iced-matcha-coconut",
    categoryId: "category-matcha-signature",
    name: "Iced Matcha Coconut",
    price: "72000",
    note: "dua tuoi + matcha",
    status: "Active",
    description: "Phong cach nhiet doi, de dua len campaign mua he va menu signature.",
    orderCount: 970,
    favoriteCount: 430,
    availableStoreIds: [
      "store-nguyen-hue",
      "store-thao-dien",
      "store-phu-my-hung",
    ],
    stockByStoreId: {
      "store-nguyen-hue": 0,
      "store-thao-dien": 3,
      "store-phu-my-hung": 2,
    },
    imagePaths: itemLibraries.icedMatchaCoconut,
  },
  {
    id: "item-roasted-oolong-milk-tea",
    categoryId: "category-milk-tea-house",
    name: "Roasted Oolong Milk Tea",
    price: "58000",
    note: "tra dam vi",
    status: "Best seller",
    description: "Vi tra ro, it ngot va phu hop tap khach van phong muon uong hang ngay.",
    franchiseRequired: true,
    franchiseNote: "Mon core de dam bao nhom khach uuong hang ngay o moi chi nhanh.",
    orderCount: 3260,
    favoriteCount: 1180,
    availableStoreIds: [
      "store-nguyen-hue",
      "store-thu-duc",
      "store-thao-dien",
      "store-phu-my-hung",
      "store-tay-ho",
    ],
    stockByStoreId: {
      "store-nguyen-hue": 20,
      "store-thu-duc": 18,
      "store-thao-dien": 12,
      "store-phu-my-hung": 14,
      "store-tay-ho": 10,
    },
    imagePaths: itemLibraries.roastedOolongMilkTea,
  },
  {
    id: "item-jasmine-pearl-milk-tea",
    categoryId: "category-milk-tea-house",
    name: "Jasmine Pearl Milk Tea",
    price: "55000",
    note: "tran chau mem",
    status: "Active",
    description: "Huong hoa nhe, texture tran chau mem va de phoi cung snack tai quan.",
    orderCount: 2080,
    favoriteCount: 760,
    availableStoreIds: [
      "store-nguyen-hue",
      "store-thu-duc",
      "store-phu-my-hung",
      "store-tay-ho",
    ],
    stockByStoreId: {
      "store-nguyen-hue": 8,
      "store-thu-duc": 6,
      "store-phu-my-hung": 7,
      "store-tay-ho": 4,
    },
    imagePaths: itemLibraries.jasminePearlMilkTea,
  },
  {
    id: "item-brown-sugar-fresh-milk",
    categoryId: "category-milk-tea-house",
    name: "Brown Sugar Fresh Milk",
    price: "60000",
    note: "sua tuoi beo",
    status: "Active",
    description: "Mon nhan dien de ban take-away, hinh anh len mau dep tren social media.",
    franchiseRequired: true,
    franchiseNote: "Mon phai co trong bo nhan dien takeaway cua he thong nhuong quyen.",
    orderCount: 2990,
    favoriteCount: 990,
    availableStoreIds: [
      "store-nguyen-hue",
      "store-thu-duc",
      "store-thao-dien",
      "store-phu-my-hung",
      "store-tay-ho",
    ],
    stockByStoreId: {
      "store-nguyen-hue": 13,
      "store-thu-duc": 11,
      "store-thao-dien": 5,
      "store-phu-my-hung": 16,
      "store-tay-ho": 8,
    },
    imagePaths: itemLibraries.brownSugarFreshMilk,
  },
  {
    id: "item-peach-oolong-tea",
    categoryId: "category-refreshers",
    name: "Peach Oolong Tea",
    price: "52000",
    note: "dao vang gion",
    status: "Seasonal",
    description: "Tra thanh mat voi dao vang gion, de dua vao combo buoi trua va mua he.",
    orderCount: 1890,
    favoriteCount: 650,
    availableStoreIds: [
      "store-thu-duc",
      "store-thao-dien",
      "store-phu-my-hung",
    ],
    stockByStoreId: {
      "store-thu-duc": 7,
      "store-thao-dien": 9,
      "store-phu-my-hung": 6,
    },
    imagePaths: itemLibraries.peachOolongTea,
  },
  {
    id: "item-yuzu-green-tea",
    categoryId: "category-refreshers",
    name: "Yuzu Green Tea",
    price: "59000",
    note: "thom thanh nhat",
    status: "Active",
    description: "Huong yuzu ro, vi thanh va hop cho nhung khach muon mon nhe, it ngot.",
    franchiseRequired: true,
    franchiseNote: "Mon refresher bat buoc de giu can bang menu xanh va de uong.",
    orderCount: 2760,
    favoriteCount: 1105,
    availableStoreIds: [
      "store-nguyen-hue",
      "store-thu-duc",
      "store-thao-dien",
      "store-phu-my-hung",
      "store-tay-ho",
    ],
    stockByStoreId: {
      "store-nguyen-hue": 15,
      "store-thu-duc": 13,
      "store-thao-dien": 12,
      "store-phu-my-hung": 10,
      "store-tay-ho": 7,
    },
    imagePaths: itemLibraries.yuzuGreenTea,
  },
  {
    id: "item-mango-jasmine-sparkling",
    categoryId: "category-refreshers",
    name: "Mango Jasmine Sparkling",
    price: "62000",
    note: "co ga nhe",
    status: "Active",
    description: "Mon co gas nhe, visual vui mat va rat hop de day tren banner mua he.",
    orderCount: 1430,
    favoriteCount: 590,
    availableStoreIds: [
      "store-nguyen-hue",
      "store-thao-dien",
      "store-phu-my-hung",
    ],
    stockByStoreId: {
      "store-nguyen-hue": 5,
      "store-thao-dien": 4,
      "store-phu-my-hung": 0,
    },
    imagePaths: itemLibraries.mangoJasmineSparkling,
  },
  {
    id: "item-matcha-roll-cake",
    categoryId: "category-bakery-dessert",
    name: "Matcha Roll Cake",
    price: "42000",
    note: "bot matcha mem",
    status: "Active",
    description: "Dessert de ket hop cung hot drinks va thuc don afternoon set.",
    orderCount: 920,
    favoriteCount: 340,
    availableStoreIds: [
      "store-nguyen-hue",
      "store-thu-duc",
      "store-tay-ho",
    ],
    stockByStoreId: {
      "store-nguyen-hue": 5,
      "store-thu-duc": 4,
      "store-tay-ho": 3,
    },
    imagePaths: itemLibraries.matchaRollCake,
  },
  {
    id: "item-butter-croissant",
    categoryId: "category-bakery-dessert",
    name: "Butter Croissant",
    price: "35000",
    note: "nuong moi sang",
    status: "Active",
    description: "Mon bakery quoc dan, phu hop ban buoi sang va combo nhanh tai counter.",
    orderCount: 1620,
    favoriteCount: 470,
    availableStoreIds: [
      "store-nguyen-hue",
      "store-thu-duc",
      "store-thao-dien",
      "store-phu-my-hung",
      "store-tay-ho",
    ],
    stockByStoreId: {
      "store-nguyen-hue": 12,
      "store-thu-duc": 9,
      "store-thao-dien": 8,
      "store-phu-my-hung": 10,
      "store-tay-ho": 7,
    },
    imagePaths: itemLibraries.butterCroissant,
  },
  {
    id: "item-tiramisu-cup",
    categoryId: "category-bakery-dessert",
    name: "Tiramisu Cup",
    price: "48000",
    note: "vi ca phe nhe",
    status: "Active",
    description: "Mon dessert co do mem va vi dam vua, de ket hop voi oolong hoac matcha.",
    orderCount: 880,
    favoriteCount: 315,
    availableStoreIds: [
      "store-nguyen-hue",
      "store-thao-dien",
      "store-phu-my-hung",
      "store-tay-ho",
    ],
    stockByStoreId: {
      "store-nguyen-hue": 0,
      "store-thao-dien": 0,
      "store-phu-my-hung": 0,
      "store-tay-ho": 0,
    },
    imagePaths: itemLibraries.tiramisuCup,
  },
];

export const initialEvents = [
  {
    id: "event-green-morning",
    storeId: "store-nguyen-hue",
    title: "Green Morning Buy 1 Get 1",
    schedule: "Thu 2 va Thu 4 | 07:00 - 10:00",
    startsAt: "2026-03-23T07:00:00+07:00",
    endsAt: "2026-03-23T10:00:00+07:00",
    location: "Tat ca chi nhanh Tea Matcha",
    summary:
      "Khuyen mai cho dong Matcha Signature de thu hut dan van phong dau ngay.",
    capacity: 120,
    bookedCount: 76,
    featuredItemIds: ["item-matcha-latte-cloud", "item-yuzu-green-tea"],
    imagePaths: eventLibraries.greenMorning,
  },
  {
    id: "event-matcha-lab",
    storeId: "store-tay-ho",
    title: "Workshop Matcha Lab",
    schedule: "Chu nhat tuan 2 moi thang | 15:00",
    startsAt: "2026-04-12T15:00:00+07:00",
    endsAt: "2026-04-12T17:00:00+07:00",
    location: "Tea Matcha Tay Ho",
    summary:
      "Khach hang trai nghiem danh bot matcha va thu vi cac style pha che moi.",
    capacity: 24,
    bookedCount: 24,
    featuredItemIds: ["item-azuki-matcha", "item-matcha-roll-cake"],
    imagePaths: eventLibraries.matchaLab,
  },
  {
    id: "event-acoustic-night",
    storeId: "store-nguyen-hue",
    title: "Acoustic Tea Night",
    schedule: "Thu 6 hang tuan | 19:30",
    startsAt: "2026-03-27T19:30:00+07:00",
    endsAt: "2026-03-27T21:30:00+07:00",
    location: "Tea Matcha Nguyen Hue",
    summary:
      "Dem nhac nho cho nhom ban tre, ket hop combo do uong va dessert.",
    capacity: 60,
    bookedCount: 41,
    featuredItemIds: ["item-brown-sugar-fresh-milk", "item-tiramisu-cup"],
    imagePaths: eventLibraries.acousticNight,
  },
  {
    id: "event-member-day",
    storeId: "store-phu-my-hung",
    title: "Member Day",
    schedule: "Ngay 15 moi thang",
    startsAt: "2026-04-15T09:00:00+07:00",
    endsAt: "2026-04-15T22:00:00+07:00",
    location: "Online va tai quan",
    summary:
      "Nhan doi diem tich luy va uu dai 15% cho thanh vien da dang ky tai khoan.",
    capacity: 180,
    bookedCount: 180,
    featuredItemIds: ["item-brown-sugar-fresh-milk", "item-peach-oolong-tea"],
    imagePaths: eventLibraries.memberDay,
  },
];

export const initialReviews = [
  {
    id: "review-001",
    userId: "user-minh-anh",
    targetType: "item",
    targetId: "item-matcha-latte-cloud",
    rating: "4.9",
    title: "Mon signature rat de nho",
    comment:
      "Vi matcha dam nhung van de uong, hop de hen ban va chay campaign tren social.",
    createdAt: "2026-03-03",
  },
  {
    id: "review-002",
    userId: "user-quang-huy",
    targetType: "item",
    targetId: "item-roasted-oolong-milk-tea",
    rating: "4.8",
    title: "Hop mua mang di moi ngay",
    comment:
      "Tra sua oolong dam vi, it ngot, rat hop mua mang di truoc gio vao ca lam.",
    createdAt: "2026-03-06",
  },
  {
    id: "review-003",
    userId: "user-bao-tran",
    targetType: "store",
    targetId: "store-thao-dien",
    rating: "4.7",
    title: "Khong gian rat chill",
    comment:
      "Chi nhanh Thao Dien nhieu cay xanh, de ngoi hoc bai va nhan vien rat de thuong.",
    createdAt: "2026-03-08",
  },
  {
    id: "review-004",
    userId: "user-thanh-nha",
    targetType: "event",
    targetId: "event-acoustic-night",
    rating: "4.9",
    title: "Dem nhac vua du",
    comment:
      "Dem acoustic co khong khi dep, am nhac vua du va combo dessert rat hop.",
    createdAt: "2026-03-09",
  },
  {
    id: "review-005",
    userId: "user-linh-chi",
    targetType: "category",
    targetId: "category-bakery-dessert",
    rating: "4.6",
    title: "Dessert de upsell",
    comment:
      "Nhom banh an kem du da dang, gia mem va de ket hop voi cac mon tra sua.",
    createdAt: "2026-03-11",
  },
  {
    id: "review-006",
    userId: "user-khanh-duy",
    targetType: "store",
    targetId: "store-nguyen-hue",
    rating: "4.8",
    title: "Hop tiep khach va ngoi nhom",
    comment:
      "Khong gian dep, phu hop tiep khach va co nhieu goc ngoi linh hoat cho team meeting.",
    createdAt: "2026-03-12",
  },
  {
    id: "review-007",
    userId: "user-minh-anh",
    targetType: "event",
    targetId: "event-matcha-lab",
    rating: "5.0",
    title: "Workshop rat co noi dung",
    comment:
      "Workshop vui, de tao noi dung review va giup khach hieu hon ve chat lieu matcha.",
    createdAt: "2026-03-15",
  },
  {
    id: "review-008",
    userId: "user-quang-huy",
    targetType: "category",
    targetId: "category-milk-tea-house",
    rating: "4.7",
    title: "Danh muc de tiep can",
    comment:
      "Category tra sua de tiep can, de ban cho dan van phong va nguoi moi den quan.",
    createdAt: "2026-03-16",
  },
  {
    id: "review-009",
    userId: "user-bao-tran",
    targetType: "store",
    targetId: "store-thu-duc",
    rating: "4.8",
    title: "Rat hop hoc bai",
    comment:
      "Chi nhanh Thu Duc sach, sang va de ngoi lau, dung chat sinh vien tri thuc.",
    createdAt: "2026-03-17",
  },
  {
    id: "review-010",
    userId: "user-linh-chi",
    targetType: "store",
    targetId: "store-phu-my-hung",
    rating: "4.7",
    title: "Khong gian de di cung gia dinh",
    comment:
      "Store Phu My Hung rong, thoang va phuc vu nhanh vao cuoi tuan.",
    createdAt: "2026-03-18",
  },
  {
    id: "review-011",
    userId: "user-minh-anh",
    targetType: "item",
    targetId: "item-brown-sugar-fresh-milk",
    rating: "4.7",
    title: "Take-away rat on",
    comment:
      "Brown sugar len visual dep, vi quen thuoc va de gioi thieu cho khach moi.",
    createdAt: "2026-03-18",
  },
  {
    id: "review-012",
    userId: "user-quang-huy",
    targetType: "item",
    targetId: "item-yuzu-green-tea",
    rating: "4.9",
    title: "Mon refresher rat de uong",
    comment:
      "Huong yuzu ro, thanh nhe va la mon nen co o moi cua hang Tea Matcha.",
    createdAt: "2026-03-19",
  },
  {
    id: "review-013",
    userId: "user-thanh-nha",
    targetType: "event",
    targetId: "event-member-day",
    rating: "4.8",
    title: "Chuong trinh member rat hop ly",
    comment:
      "Member Day giup khach quay lai tot hon va de ket hop voi uu dai mon core.",
    createdAt: "2026-03-19",
  },
  {
    id: "review-014",
    userId: "user-ngoc-han",
    targetType: "item",
    targetId: "item-matcha-latte-cloud",
    rating: "4.8",
    title: "Foam min va len anh dep",
    comment:
      "Mon nay len ly rat dep, vi nhe va hop cho nhung buoi gap ban o Nguyen Hue.",
    createdAt: "2026-03-19",
  },
  {
    id: "review-015",
    userId: "user-tuan-kiet",
    targetType: "item",
    targetId: "item-roasted-oolong-milk-tea",
    rating: "4.7",
    title: "Tra dam, hoc bai de tap trung",
    comment:
      "Mua o chi nhanh Thu Duc rat hop luc ngoi hoc lau, vi dam ma khong bi ngot gắt.",
    createdAt: "2026-03-20",
  },
  {
    id: "review-016",
    userId: "user-phuong-linh",
    targetType: "item",
    targetId: "item-brown-sugar-fresh-milk",
    rating: "4.6",
    title: "Mon take-away quoc dan",
    comment:
      "Thuong dat mang di khi di lam, visual dep va de uong nen rat de gioi thieu ban be.",
    createdAt: "2026-03-20",
  },
  {
    id: "review-017",
    userId: "user-ngoc-han",
    targetType: "item",
    targetId: "item-yuzu-green-tea",
    rating: "4.8",
    title: "Thanh va sach vi",
    comment:
      "Yuzu Green Tea uong rat sach mieng, hop ngay nang va ngoi o khong gian nhieu cay xanh.",
    createdAt: "2026-03-20",
  },
  {
    id: "review-018",
    userId: "user-minh-anh",
    targetType: "item",
    targetId: "item-azuki-matcha",
    rating: "4.7",
    title: "Texture vui va de nho",
    comment:
      "Azuki an voi matcha rat hop, mon nay co cam giac premium hon cac mon thong thuong.",
    createdAt: "2026-03-20",
  },
  {
    id: "review-019",
    userId: "user-bao-tran",
    targetType: "item",
    targetId: "item-jasmine-pearl-milk-tea",
    rating: "4.6",
    title: "De tiep can voi nhieu ban tre",
    comment:
      "Tran chau mem, huong hoa nhe nen ai trong nhom cung de chon khi di dong nguoi.",
    createdAt: "2026-03-20",
  },
  {
    id: "review-020",
    userId: "user-linh-chi",
    targetType: "item",
    targetId: "item-peach-oolong-tea",
    rating: "4.5",
    title: "Tra dao mat va de uong",
    comment:
      "Mon nay hop mua trua, vi dao ro va rat de len combo voi banh ngan.",
    createdAt: "2026-03-20",
  },
  {
    id: "review-021",
    userId: "user-tuan-kiet",
    targetType: "store",
    targetId: "store-nguyen-hue",
    rating: "4.9",
    title: "Flagship rat xung dang",
    comment:
      "Khong gian business-casual rat dep, ngoi tiep khach hay lam viec deu on va chuyen nghiep.",
    createdAt: "2026-03-20",
  },
  {
    id: "review-022",
    userId: "user-phuong-linh",
    targetType: "store",
    targetId: "store-thao-dien",
    rating: "4.8",
    title: "Thoang va rat de thuong",
    comment:
      "Rat thich khong gian mo, nhieu cay xanh va anh sang tu nhien cua chi nhanh Thao Dien.",
    createdAt: "2026-03-20",
  },
  {
    id: "review-023",
    userId: "user-ngoc-han",
    targetType: "store",
    targetId: "store-thu-duc",
    rating: "4.7",
    title: "Di hoc hay gap ban deu hop",
    comment:
      "Ban dai, o cam day du va am thanh de chiu nen hoc nhom hoac lam viec deu rat on.",
    createdAt: "2026-03-20",
  },
  {
    id: "review-024",
    userId: "user-bao-tran",
    targetType: "store",
    targetId: "store-nguyen-hue",
    rating: "4.8",
    title: "Sang nhung van de chill",
    comment:
      "Store sang trong nhung khong bi xa cach, buoi toi len den am va rat hop de ngoi lau.",
    createdAt: "2026-03-20",
  },
  {
    id: "review-025",
    userId: "user-minh-anh",
    targetType: "store",
    targetId: "store-thu-duc",
    rating: "4.9",
    title: "Sach se dung chat Tea Matcha",
    comment:
      "Chi nhanh Thu Duc giu duoc DNA sach va chill, nhan vien than thien va mon core luon on dinh.",
    createdAt: "2026-03-20",
  },
];

export const loginBenefits = [
  "Quan ly thong tin thanh vien va uu dai theo tung chi nhanh.",
  "Theo doi doanh thu, ca lam va danh sach mon ban chay trong ngay.",
  "Cap nhat su kien, combo mua vu va phan hoi cua khach hang.",
];
